### ISSUE TITLE
Custom ITelemetryInitializer being called multiple times

### ISSUE THREAD

**Issue by KenBrannigan** [aspnet/Microsoft.AspNet.TelemetryCorrelation#31]
Hello,
We have a custom ITelemetryInitializer that looks to see if the ITelemetry is an ExceptionTelemetry type and if so does some custom logging. When we upgraded to the latest AI NuGet packages we noticed a new module added to our web.config, TelemetryCorrelationHttpModule. With this module in the web.config we noticed our custom ITelemetryInitializer is being called more than once where the ITelemetry is an ExceptionTelemetry. If we remove this module it is only called once.

Is this expected behavior and if so why? also any suggestion on how to identify the first call from the rest so our custom logging is only done once?

Take care,
Ken

**Comment by lmolkova** [comment]
@KenBrannigan  this question belongs to ApplicaitonInsights  Web SDK: https://github.com/Microsoft/ApplicationInsights-dotnet-server

you should expect that telemetry initializers could be called more than once - this is expected behavior of the ApplicationInsights SDK. So, please ensure the initializer checks that it's already been called on the same telemetry (e.g. some property it sets is there already).

Removing this module also prevents requests from being tracked in ApplicationInsights and affects exceptions tracking as well.
